### ISSUE TITLE
How do I run the program on Windows?

### ISSUE THREAD

**Issue by Edilzin** [coderarjob/kpdfsync#10]
Hi, I'm a newbie and I'm trying to test the program but I don't know how to run it. I'm looking for an .exe file. Thanks!

**Comment by Edilzin** [comment]
Question solved. I installed Java Runtime and everything worked. Thanks!

Link: https://www.java.com/en/download/ie_manual.jsp

**Comment by coderarjob** [comment]
Great! Sorry I could not reply in time. 

Just make sure you get the latest [kpdfsync-0.10.0-alpha](https://github.com/coderarjob/kpdfsync/releases/tag/0.10.0-alpha) version (It is in pre-release state, but includes many bug fixes). Download the [kpdfsync-0.10.0-alpha.zip](https://github.com/coderarjob/kpdfsync/releases/download/0.10.0-alpha/kpdfsync-0.10.0-alpha.zip) and run `kpdfsync.bat` on windows.

Anyways here are the [prerequisites](https://github.com/coderarjob/kpdfsync#requirements).
Do let me know if you face any issues.
