### ISSUE TITLE
"Empty or invalid clippings file"

### ISSUE THREAD

**Issue by Raagaception** [coderarjob/kpdfsync#7]
I'm getting the folloiwing error upon trying to import the ``My Clippings.txt`` file<br>![image](https://user-images.githubusercontent.com/72780589/178148294-6e91b3c7-cb2c-43f1-af95-acd521cfe451.png)

Log looks something like<br>![image](https://user-images.githubusercontent.com/72780589/178148339-936e506c-b0fa-48b8-8a0e-71d3fdb3c143.png)

What am I doing wrong here? Here's my clippings file if that helps to troubleshoot - [My Clippings.txt](https://github.com/coderarjob/kpdfsync/files/9079214/My.Clippings.txt)

**Comment by coderarjob** [comment]
Let me have a look and will get back to you. Thanks

**Comment by coderarjob** [comment]
Found the problem. Your clippings file format seems to be a little different. Would you please tell, which Kindle and what Firmware version are you using.

I have attached a 'converted' version of your My Clippings, which works with the current kpdfsync version. But please let me know your Kindle and Firmware version so I can make the change.

[My.Clippings.txt](https://github.com/coderarjob/kpdfsync/files/9082710/My.Clippings.txt)

**Comment by Raagaception** [comment]
It's honestly ancient; I wasn't aware the format varied Kindle to Kindle, but in hindsight it should've been obvious! 

Mine is the "Kindle 3 Keyboard" released in 2010, with firmware version ``Kindle 3.4.3 (3543620001)``.

**Comment by coderarjob** [comment]
Issue is now fixed. Please check the Pre-Release 0.10.0 version.
https://github.com/coderarjob/kpdfsync/releases/tag/0.10.0-alpha

User now have to option to select the Kindle Clippings format. In your case use the 'Old format'

![issue7_fixed](https://user-images.githubusercontent.com/2406071/179337054-8bf73ef5-e6e6-43a4-89cc-13d75806de3d.png)
